# Generated by Django 4.2.2 on 2023-10-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('hours_worked', models.FloatField()),
                ('rate_per_hour', models.FloatField()),
                ('supplier_name', models.CharField(max_length=100)),
                ('purchase_order', models.CharField(max_length=100)),
            ],
        ),
    ]
